services:
  - type: web
    name: rss-analysis-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: ENV
        value: production
      - key: REDIS_HOST
        fromService:
          type: redis
          name: rss-redis
          property: host
      - key: REDIS_PASSWORD
        sync: false
      - key: MODAL_TOKEN_ID
        sync: false
      - key: MODAL_TOKEN_SECRET
        sync: false
    autoDeploy: true
    healthCheckPath: /health

  - type: redis
    name: rss-redis
    ipAllowList: []
    plan: free 